CREATE TABLE MOVIES 
   (	MOVIEID NUMBER(*, 0), 
	TITLE VARCHAR2(150 BYTE), 
	YEAR NUMBER, 
	AC_RATING FLOAT(126), 
	TC_RATING FLOAT(126), 
	A_RATING FLOAT(126), 
	AC_NUM_REVIEWS NUMBER(*,0), 
	TC_NUM_REVIEWS NUMBER(*,0), 
	A_NUM_REVIEWS NUMBER(*,0),
	PRIMARY KEY (MOVIEID)
   );

CREATE TABLE TAGS 
   (	TAG_ID NUMBER(*,0), 
	TAG_VALUE VARCHAR2(50 BYTE) NOT NULL ENABLE,
	PRIMARY KEY (TAG_ID)
   );

CREATE TABLE MOVIE_ACTORS 
   (	MOVIEID NUMBER(*,0) NOT NULL ENABLE, 
	ACTOR_ID VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	ACTOR_NAME VARCHAR2(60 BYTE), 
	RANKING NUMBER(*,0)
   );

CREATE TABLE MOVIE_COUNTRY 
   (	MOVIEID NUMBER(*, 0), 
	COUNTRY VARCHAR2(40 BYTE),
	PRIMARY KEY(MOVIEID, COUNTRY)
   );

CREATE TABLE MOVIE_DIRECTORS 
   (	MOVIEID NUMBER(*,0) NOT NULL ENABLE, 
	DIRECTOR_ID VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	DIRECTOR_NAME VARCHAR2(60 BYTE)
   );

CREATE TABLE MOVIE_GENRE 
   (	MOVIEID NUMBER(*,0) NOT NULL ENABLE, 
	GENRE_NAME VARCHAR2(40 BYTE),
	PRIMARY KEY(MOVIEID, GENRE_NAME)
   );

CREATE TABLE MOVIE_TAG 
   (	MOVIEID NUMBER(*,0) NOT NULL ENABLE, 
	TAG_ID NUMBER(*,0) NOT NULL ENABLE, 
	TAG_WEIGHT NUMBER(*,0)
   );

CREATE TABLE USER_RATING 
   (	USER_ID NUMBER(*, 0) NOT NULL ENABLE, 
	MOVIEID NUMBER(*, 0) NOT NULL ENABLE, 
	RATING FLOAT(126), 
	TIMESTAMP NUMBER(*, 0),
	PRIMARY KEY (USER_ID, MOVIEID)
   );

CREATE TABLE USER_TAG 
   (	USER_ID NUMBER(*,0), 
	MOVIEID NUMBER(*,0) NOT NULL ENABLE, 
	TAG_ID NUMBER(*,0) NOT NULL ENABLE, 
	TIMESTAMP NUMBER(*, 0)
   );

CREATE INDEX INDEX1 ON MOVIE_ACTORS (ACTOR_NAME ASC);

CREATE INDEX INDEX2 ON MOVIE_COUNTRY (COUNTRY ASC);

CREATE INDEX INDEX3 ON MOVIE_DIRECTORS (DIRECTOR_NAME ASC);

CREATE INDEX INDEX4 ON MOVIE_GENRE (GENRE_NAME ASC);

CREATE INDEX INDEX5 ON MOVIE_TAG (MOVIEID ASC);

CREATE INDEX INDEX6 ON USER_RATING (USER_ID ASC);

