DROP TABLE USER_TAG;
DROP TABLE USER_RATING;
DROP TABLE MOVIE_TAG;
DROP TABLE TAGS;
DROP TABLE MOVIE_GENRE;
DROP TABLE MOVIE_DIRECTORS;
DROP TABLE MOVIE_COUNTRY;
DROP TABLE MOVIE_ACTORS;
DROP TABLE MOVIES;


